"""initialize_database

Revision ID: 6bfebb4af6ba
Revises:
Create Date: 2022-11-02 11:58:51.077956

"""
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import parser.models as models

# revision identifiers, used by Alembic.
revision = "6bfebb4af6ba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grpc_status",
        sa.Column(
            "record_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column("job_request", sa.String(), nullable=True),
        sa.Column("status", sa.Enum(models.Status), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=True),
        sa.Column("date_of_last_attempt", sa.DateTime(), nullable=True),
        sa.Column("date_of_last_success", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("record_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grpc_status")
    op.execute("DROP TYPE status")

    # ### end Alembic commands ###
